version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=9090
    ports:
      - "9090:9090"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    command: [ 'start-dev --import-realm' ]